export const apiModules = [
  {
    id: "uploaders",
    name: "Media Uploaders Pack",
    description: "Upload image assets and files directly to CDNs like Imgur, Catbox, and Top4Top.",
    status: "active",
    endpointsCount: 10,
  },
  {
    id: "downloaders",
    name: "Media Downloaders Pack",
    description: "Download video and audio streams directly from platforms like TikTok, Instagram, YouTube, Spotify, SoundCloud, Twitter/X, Threads, Facebook, Bilibili, SnackVideo, CapCut, CocoFun, Douyin, YouTube Community, GitHub, Google Drive, MediaFire, MEGA, NPM, Pinterest, RedNote (Xiaohongshu), Scribd, SFile.co, TeraBox, Dailymotion, Pornhub, PornHD, and XNXX.",
    status: "active",
    endpointsCount: 28,
  },
  {
    id: "news",
    name: "News Scrapers Pack",
    description: "Fetch latest news from 37 sources: ST, CNA, BBC, CNN, Mothership, Al Jazeera, ABC, WaPo, AP News, Fox News, Reuters, CBS, NYT, MS NOW, WSJ, The Guardian, TIME, Sky News, NPR, Bloomberg, The Times, DW, NHL, News24, Newsweek, Yahoo News, U.S. News, NBC News, NASA, Detroit Free Press, MassLive, WMTV 15 News, Forbes, Euronews, USA Today, The Independent, and The Punch.",
    status: "active",
    endpointsCount: 37,
  },
  {
    id: "local-news",
    name: "Local News Scrapers Pack",
    description: "Fetch latest local news from Indonesian sources: Detik News, Kompas News, CNN Indonesia, Liputan6 News, Sindonews, Antara News, BMKG News, Tempo, Bisnis.com, Okezone, CNBC Indonesia, TIMES Indonesia, Inilah.com, Bank Indonesia, Hukumonline, Media Indonesia, Berita Jakarta, Tangerang Kota, Kompas TV, VIVA News, iNews, Terkini News, CNA Indonesia, Merdeka News, and The Jakarta Post.",
    status: "active",
    endpointsCount: 25,
  },
  {
    id: "image-tools",
    name: "Image Tools Pack",
    description: "Process and edit images using tools like background removal, AI upscaling, vintage filters, color inversion, image flipping, retro pixelation, rounded corners, image splitting, adding noise, image blurring, image sharpening, solarize filters, glow effects, posterize effects, blur face effects, and AI image enhancement.",
    status: "active",
    endpointsCount: 16,
  },
  {
    id: "qr-tools",
    name: "QR Tools Pack",
    description: "Generate, style, and decode high-quality QR codes and barcodes online instantly.",
    status: "active",
    endpointsCount: 2,
  },
  {
    id: "shortlink-tools",
    name: "Shortlink Tools Pack",
    description: "Generate and manage shortened urls using popular platforms like TinyURL, is.gd, v.gd, ulvis.net, da.gd, and cleanuri.com.",
    status: "active",
    endpointsCount: 6,
  },
  {
    id: "ai-chat",
    name: "AI Chat Tools Pack",
    description: "Interact with state-of-the-art language models like Llama 3.3, Groq Compound, Qwen 2.5, MiniMax, DeepSeek, Kimi, GLM 5.1, Nemotron Ultra, ChatGPT, IBM Granite 4.0, Mistral AI, QuillBot AI, Perplexity AI, Google Gemini, Pollinations AI, Asynt AI, Muslim AI, Gita AI, PowerBrain AI, Felo AI, MathGPT, Jeeves AI, Sahabat AI, Aya AI, Ansari AI, Olabiba AI, Gemma 4, DeepSeek R1, and FeelBetter AI.",
    status: "active",
    endpointsCount: 29,
  },
  {
    id: "ai-image",
    name: "AI Image Generator Pack",
    description: "Generate stunning AI images using state-of-the-art models like Flux 1 Schnell, Flux 2, Magic Studio, Z-Image Turbo, Qwen Image, ERNIE Image Turbo, and Ideogram 4.",
    status: "active",
    endpointsCount: 7,
  },
  {
    id: "bmkg",
    name: "BMKG Indonesia Pack",
    description: "Akses data gempa terkini, gempa terbaru, gempa dirasakan, dan berita resmi dari BMKG (Badan Meteorologi, Klimatologi, dan Geofisika Indonesia).",
    status: "active",
    endpointsCount: 4,
  },
  {
    id: "informations",
    name: "Informations Pack",
    description: "Akses informasi cuaca, cari kode pos, jadwal TV, dan jadwal pertandingan sepak bola dari OneFootball.",
    status: "active",
    endpointsCount: 4,
  },
];
