import type { DocTopic } from '../../types';

const googleLanguages = [
  { value: 'id', label: 'Indonesia (Indonesian)' },
  { value: 'en', label: 'Inggris (English)' },
  { value: 'ja', label: 'Jepang (Japanese)' },
  { value: 'ko', label: 'Korea (Korean)' },
  { value: 'zh-CN', label: 'Tiongkok - Sederhana (Chinese Simplified)' },
  { value: 'zh-TW', label: 'Tiongkok - Tradisional (Chinese Traditional)' },
  { value: 'ar', label: 'Arab (Arabic)' },
  { value: 'fr', label: 'Prancis (French)' },
  { value: 'de', label: 'Jerman (German)' },
  { value: 'es', label: 'Spanyol (Spanish)' },
  { value: 'ru', label: 'Rusia (Russian)' },
  { value: 'it', label: 'Italia (Italian)' },
  { value: 'pt', label: 'Portugis (Portuguese)' },
  { value: 'nl', label: 'Belanda (Dutch)' },
  { value: 'tr', label: 'Turki (Turkish)' },
  { value: 'vi', label: 'Vietnam (Vietnamese)' },
  { value: 'th', label: 'Thailand (Thai)' },
  { value: 'tl', label: 'Filipina (Tagalog)' },
  { value: 'hi', label: 'India (Hindi)' },
  { value: 'ms', label: 'Melayu (Malay)' },
  { value: 'la', label: 'Latin' },
  { value: 'jw', label: 'Jawa (Javanese)' },
  { value: 'su', label: 'Sunda (Sundanese)' },
  { value: 'af', label: 'Afrikaans' },
  { value: 'sq', label: 'Albania (Albanian)' },
  { value: 'am', label: 'Amharik (Amharic)' },
  { value: 'hy', label: 'Armenia (Armenian)' },
  { value: 'as', label: 'Assam (Assamese)' },
  { value: 'ay', label: 'Aymara' },
  { value: 'az', label: 'Azerbaijan (Azerbaijani)' },
  { value: 'bm', label: 'Bambara' },
  { value: 'eu', label: 'Basque' },
  { value: 'be', label: 'Belarus (Belarusian)' },
  { value: 'bn', label: 'Bengali' },
  { value: 'bho', label: 'Bhojpuri' },
  { value: 'bs', label: 'Bosnia (Bosnian)' },
  { value: 'bg', label: 'Bulgaria (Bulgarian)' },
  { value: 'ca', label: 'Katalan (Catalan)' },
  { value: 'ceb', label: 'Cebuano' },
  { value: 'ny', label: 'Chichewa' },
  { value: 'co', label: 'Korsika (Corsican)' },
  { value: 'hr', label: 'Kroasia (Croatian)' },
  { value: 'cs', label: 'Ceko (Czech)' },
  { value: 'da', label: 'Denmark (Danish)' },
  { value: 'dv', label: 'Dhivehi' },
  { value: 'doi', label: 'Dogri' },
  { value: 'eo', label: 'Esperanto' },
  { value: 'et', label: 'Esti (Estonian)' },
  { value: 'ee', label: 'Ewe' },
  { value: 'fi', label: 'Finlandia (Finnish)' },
  { value: 'fy', label: 'Frisia (Frisian)' },
  { value: 'gl', label: 'Galisia (Galician)' },
  { value: 'ka', label: 'Georgia (Georgian)' },
  { value: 'el', label: 'Yunani (Greek)' },
  { value: 'gn', label: 'Guarani' },
  { value: 'gu', label: 'Gujarat (Gujarati)' },
  { value: 'ht', label: 'Kreol Haiti (Haitian Creole)' },
  { value: 'ha', label: 'Hausa' },
  { value: 'haw', label: 'Hawaii (Hawaiian)' },
  { value: 'iw', label: 'Ibrani (Hebrew)' },
  { value: 'hmn', label: 'Hmong' },
  { value: 'hu', label: 'Hongaria (Hungarian)' },
  { value: 'is', label: 'Islandia (Icelandic)' },
  { value: 'ig', label: 'Igbo' },
  { value: 'ilo', label: 'Ilocano' },
  { value: 'ga', label: 'Irlandia (Irish)' },
  { value: 'kn', label: 'Kannada' },
  { value: 'kk', label: 'Kazakh' },
  { value: 'km', label: 'Khmer' },
  { value: 'rw', label: 'Kinyarwanda' },
  { value: 'gom', label: 'Konkani' },
  { value: 'kri', label: 'Krio' },
  { value: 'ku', label: 'Kurdi - Kurmanji (Kurdish)' },
  { value: 'ckb', label: 'Kurdi - Sorani' },
  { value: 'ky', label: 'Kirgiz (Kyrgyz)' },
  { value: 'lo', label: 'Lao' },
  { value: 'lv', label: 'Latvia (Latvian)' },
  { value: 'ln', label: 'Lingala' },
  { value: 'lt', label: 'Lituania (Lithuanian)' },
  { value: 'lg', label: 'Luganda' },
  { value: 'lb', label: 'Luksemburg (Luxembourgish)' },
  { value: 'mk', label: 'Makedonia (Macedonian)' },
  { value: 'mai', label: 'Maithili' },
  { value: 'mg', label: 'Malagasi (Malagasy)' },
  { value: 'ml', label: 'Malayalam' },
  { value: 'mt', label: 'Malta (Maltese)' },
  { value: 'mi', label: 'Maori' },
  { value: 'mr', label: 'Marathi' },
  { value: 'mni-Mtei', label: 'Meiteilon (Manipuri)' },
  { value: 'lus', label: 'Mizo' },
  { value: 'mn', label: 'Mongolia (Mongolian)' },
  { value: 'my', label: 'Myanmar (Burmese)' },
  { value: 'ne', label: 'Nepal (Nepali)' },
  { value: 'no', label: 'Norwegia (Norwegian)' },
  { value: 'or', label: 'Odia (Oriya)' },
  { value: 'om', label: 'Oromo' },
  { value: 'ps', label: 'Pashto' },
  { value: 'fa', label: 'Persia (Persian)' },
  { value: 'pl', label: 'Polandia (Polish)' },
  { value: 'pa', label: 'Punjabi' },
  { value: 'qu', label: 'Quechua' },
  { value: 'ro', label: 'Rumania (Romanian)' },
  { value: 'sm', label: 'Samoa (Samoan)' },
  { value: 'sa', label: 'Sanskerta (Sanskrit)' },
  { value: 'gd', label: 'Gaelik Skotlandia (Scots Gaelic)' },
  { value: 'nso', label: 'Sepedi' },
  { value: 'sr', label: 'Serbia (Serbian)' },
  { value: 'st', label: 'Sesotho' },
  { value: 'sn', label: 'Shona' },
  { value: 'sd', label: 'Sindhi' },
  { value: 'si', label: 'Sinhala' },
  { value: 'sk', label: 'Slowakia (Slovak)' },
  { value: 'sl', label: 'Slowenia (Slovenian)' },
  { value: 'so', label: 'Somalia (Somali)' },
  { value: 'sw', label: 'Swahili' },
  { value: 'sv', label: 'Swedia (Swedish)' },
  { value: 'tg', label: 'Tajikistan (Tajik)' },
  { value: 'ta', label: 'Tamil' },
  { value: 'tt', label: 'Tatar' },
  { value: 'te', label: 'Telugu' },
  { value: 'ti', label: 'Tigrinya' },
  { value: 'ts', label: 'Tsonga' },
  { value: 'tk', label: 'Turkmen' },
  { value: 'ak', label: 'Twi' },
  { value: 'uk', label: 'Ukraina (Ukrainian)' },
  { value: 'ur', label: 'Urdu' },
  { value: 'ug', label: 'Uighur (Uyghur)' },
  { value: 'uz', label: 'Uzbek' },
  { value: 'cy', label: 'Wales (Welsh)' },
  { value: 'xh', label: 'Xhosa' },
  { value: 'yi', label: 'Yiddi (Yiddish)' },
  { value: 'yo', label: 'Yoruba' },
  { value: 'zu', label: 'Zulu' }
];

const sourceLanguages = [
  { value: 'auto', label: 'Deteksi Otomatis (Auto Detect)' },
  ...googleLanguages
];

export const translateRoute: DocTopic = {
  id: 'translate',
  title: 'Google Translate',
  category: 'Tools',
  method: 'GET',
  path: '/api/tools/translate',
  pathTemplate: '/api/tools/:slug',
  description: 'Terjemahkan teks ke bahasa apa pun.',
  parameters: [
    { name: 'text', type: 'text', required: true, desc: 'Text to translate.' },
    { name: 'to', type: 'select', required: false, desc: 'Target language.', options: googleLanguages },
    { name: 'from', type: 'select', required: false, desc: 'Source language.', options: sourceLanguages }
  ],
  payloadTemplate: {
    text: 'hello world',
    to: 'id',
    from: 'auto'
  }
};
